[versions]

interfaces = "1.0.0-SNAPSHOT"
minecommons = "1.4"
bstats = "2.2.1"
junit = "5.7.2"

# Paper
paper = "1.18.1-R0.1-SNAPSHOT"
paperProtocolLib = "4.8.0-SNAPSHOT"

[libraries]

interfacesCore = { group = "org.incendo.interfaces", name = "interfaces-core", version.ref = "interfaces" }
minecommonsCore = { group = "com.github.aecsocket", name = "minecommons-core", version.ref = "minecommons" }

jupiterApi = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
jupiterEngine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }

paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
paperBstats = { group = "org.bstats", name = "bstats-bukkit", version.ref = "bstats" }
paperInterfaces = { group = "org.incendo.interfaces", name = "interfaces-paper", version.ref = "interfaces" }
paperMinecommons = { group = "com.github.aecsocket", name = "minecommons-paper", version.ref = "minecommons" }
paperProtocolLib = { group = "com.comphenix.protocol", name = "ProtocolLib", version.ref = "paperProtocolLib" }

[bundles]

junit = [ "jupiterApi", "jupiterEngine" ]
