[versions]

junit = "5.7.2"
minecraft = "1.18.2"

minecommons = "1.4.2-SNAPSHOT"
findBugs = "3.0.2"
bstats = "2.2.1"

[libraries]

jupiterApi = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
jupiterEngine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }

minecommons = { group = "com.github.aecsocket", name = "minecommons-core", version.ref = "minecommons" }
findBugs = { group = "com.google.code.findbugs", name = "jsr305", version.ref = "findBugs" }

bstatsPaper = { group = "org.bstats", name = "bstats-bukkit", version.ref = "bstats" }
minecommonsPaper = { group = "com.github.aecsocket", name = "minecommons-paper", version.ref = "minecommons" }

[bundles]

junit = [ "jupiterApi", "jupiterEngine" ]
