name: "Publish docs"

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "adopt"
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            paper/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/*.gradle.kts', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-${{ secrets.CACHE_VERSION }}-

      - name: "Build docs"
        run: ./gradlew dokkaHtmlMultiModule
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.DOCS_TOKEN }}
          repository-name: aecsocket/aecsocket.github.io
          branch: gh-pages
          folder: build/dokka/htmlMultiModule
          target-folder: sokol/dokka
          git-config-name: github-actions[bot]
          git-config-email: 41898282+github-actions[bot]@users.noreply.github.com
