name: "Sokol"
description: "@description@"
main: "@group@.paper.Sokol"
version: "@version@"
api-version: "1.19"
authors: [ "aecsocket" ]
website: "https://phosphorous.gitlab.io/sokol"

depend: [ "KtRuntime", "CraftBullet", "Alexandria" ]
